### PR TITLE
Add ros2_description_solo

### PR DESCRIPTION
**Pull request by swuuu**
I have added a package with the files describing SOLO in this pull request. In case this helps, I have used it with the packages ros2_control_solo_bringup and ros2_control_test_nodes found [here](https://github.com/swuuu/ros2_control_solo).

### CODE REVIEW

**Comment by swuuu** [comment]
@Lhumd, @MaximilienNaveau, @olivier-stasse

**Comment by olivier-stasse** [comment]
Dear @swuuu,
Thanks a lot for your interest.
As we want to keep things atomic, could you instead make your PR to https://github.com/stack-of-tasks/ros2_control_solo ?
I just created this new repository for SOLO.
This repo is dedicated to bolt and it would make things complicated to do it somewhere else.

While making the new PR, could make sure that you include only needed directories ?

The following directories *should* be removed:
```
.idea
cmake-build-debug
log
```

**Review by olivier-stasse — CHANGES_REQUESTED** [review]
Please remove the directories 
```
.idea
cmake-build-debug
log
```
and propose your PR on ros2_control_solo repository

**Comment by swuuu** [comment]
Dear @olivier-stasse,

Thank you for your update. I will do that.

**Comment by olivier-stasse** [comment]
This PR is superseeded by the following PR stack-of-tasks/ros2_control_bolt#1 in the repository ```stack-of-tasks/ros2_control_bolt```

**Pull request closed without merging**
